### ISSUE TITLE
handleOpen and handleClose were coming up undefined. handleOpen (e) {     this.setState({ modalOpen: true });    } fixes it.

### ISSUE THREAD

**Issue by contidominic** [cefjoeii/mern-crud#20]

**Comment by contidominic** [comment]
handleOpen and handleClose were coming up undefined. handleOpen (e) {     this.setState({ modalOpen: true });    } fixes it.

**Comment by cefjoeii** [comment]
Hi! Not quite sure what you meant by coming up undefined. Anyways, I did some updates on the libraries and the front-end. Thank you.
