### ISSUE TITLE
What does validators on the age on gender on backend means

### ISSUE THREAD

**Issue by Mayank-MP05** [cefjoeii/mern-crud#21]
Are contributors supposed to add the custom validators based on express validators?
- For Age = ```5 <= age <= 130```
- For Gender = either ```'M','F',''```

**Comment by cefjoeii** [comment]
Hey! 😁

For the **Age**, they're just an arbitrary range that made sense (at least to me) when working on this project at that time.
For the **Gender**, if I can remember, I wanted to set the value to an empty string if it's neither an 'M' or an 'F'
