### ISSUE TITLE
mongodb 3.6

### ISSUE THREAD

**Issue by jaydestro** [cefjoeii/mern-crud#3]
i am going to be featuring your app in a upcoming blog post, can you review the 3.6 notice and provide me with any potential workarounds you plan on?

**Comment by cefjoeii** [comment]
Hi. Upon checking the site, the current stable release for MongoDB is v3.4.x and the plan is to settle on v3.4.2 in the meantime. If ever you can find a way, feel free to improve this little app. Thanks.
