### ISSUE TITLE
[BUG]:Validation Issue All Field Should be mark required

### ISSUE THREAD

**Issue by alijafri691** [cefjoeii/mern-crud#55]
if we don't provide the Gender field it still Add the List 

Expected Behavior:
It should show error if all field are not given

![image](https://github.com/user-attachments/assets/deda4c3b-0b0b-410c-b108-bcd6dab1afc8)

**Comment by cefjoeii** [comment]
We've received some objections in the past and they wanted to remove the validation specifically for gender. Thanks for pointing this out!

**Comment by alijafri691** [comment]
Ohh okey!!!
