### ISSUE TITLE
Issue with Dev

### ISSUE THREAD

**Issue by sc305495** [cefjoeii/mern-crud#9]
When I cd react-src, run npm install, and then npm start the react app starts just fine on 4200 but when I click to add a user or anything like that that starts one of the containers it renders far off into the top left of the screen.

Has anyone else seen this problem?  I've tested on IE 11, and Chrome.

**Comment by JesusMartinezRuano** [comment]
Yes, it happened to me. Also changed to responsive view tablet/mobile, no way.

**Comment by cefjoeii** [comment]
@rehan-sattar created a PR here #11
